/**
 * AI set-builder — a free-text brief → a reviewable DRAFT GameSet CONFIG. Mirrors
 * challenge-ai.service (draft-out, two-flag {configured, draft}, safeParse, never
 * throws). The AI composes CONFIGURATION ONLY (which games, timings, difficulty,
 * counts, practice flags); it NEVER authors game content — puzzles are generated
 * by the system from a seed. Everything the model returns is validated + clamped
 * against the real registry and gameSetUpsertSchema before it reaches an operator.
 *
 * Metering, governor shedding, and refunds are automatic at the LLM gateway once
 * `collegeId` is in the policy (feature "game_build"). A null return (no provider,
 * exhausted credits, or unusable output) surfaces as draft:null → "AI unavailable,
 * compose manually", never a broken draft.
 */
import {
  GAME_CATALOG,
  callLlmChatJson,
  gameSetUpsertSchema,
  hasLlmRouter,
  type AiBuildGameSetResponse,
  type GameKey,
  type GameSetUpsert,
} from "@codeapt/shared";

/** The non-dev games an operator may compose with (drives the prompt + the
 * gameKey allow-list). `_probe` (devOnly) is never offered. */
function availableGames(): { key: GameKey; name: string; interactive: boolean }[] {
  return GAME_CATALOG.filter((g) => !g.devOnly).map((g) => ({
    key: g.key,
    name: g.displayName,
    interactive: g.interactive,
  }));
}

const SYSTEM_PROMPT = [
  "You configure an adaptive APTITUDE GAME SET for a training platform.",
  "You choose ONLY configuration: which games to include, their order, per-game",
  "duration, starting difficulty, whether skipping is allowed, how many questions,",
  "the selection mode, attempt cap, and practice flags.",
  "",
  "You do NOT write any game content — the puzzles themselves are generated by the",
  "system from a random seed. Never invent questions, grids, mazes, or answers.",
  "",
  "Respond with STRICT JSON ONLY (no prose, no code fences), of the shape:",
  '{ "title": string, "description": string,',
  '  "games": [ { "gameKey": string, "durationSeconds": number, "startingDifficulty": "easy"|"moderate"|"hard", "allowSkip": boolean, "maxQuestions": number, "onWallHit"?: "block"|"reset" } ],',
  '  "selectionMode": "fixed"|"random_n_of_pool", "pickCount"?: number,',
  '  "perQuestionTimerSeconds": number, "instantFeedback": boolean, "maxAttempts": number }',
  "",
  "Only use gameKey values from the provided list. durationSeconds is 10..3600.",
  "maxQuestions 0 means unlimited within the clock. onWallHit applies to door_key only.",
].join("\n");

function buildUserPrompt(brief: string, forCollege: boolean): string {
  const games = availableGames()
    .map((g) => `- ${g.key} (${g.name})${g.interactive ? " [interactive]" : ""}`)
    .join("\n");
  return [
    `Audience: ${forCollege ? "a college assigning this to its students" : "the platform catalog"}.`,
    "Available games:",
    games,
    "",
    "Operator brief:",
    brief,
    "",
    "Produce ONE game set configuration as strict JSON.",
  ].join("\n");
}

// --- Validation: reject vs clamp, per field (see the step report) -----------

const DIFFICULTIES = new Set(["easy", "moderate", "hard"]);

function clampInt(v: unknown, lo: number, hi: number, fallback: number): number {
  const n = typeof v === "number" && Number.isFinite(v) ? Math.round(v) : fallback;
  return Math.min(hi, Math.max(lo, n));
}

/**
 * Turn the model's loose JSON into a valid GameSetUpsert, or null if it can't.
 *   - gameKey: REJECT (drop) unknown/dev keys — a hallucinated key has no valid
 *     nearest value; if no real games survive, the draft is unusable → null.
 *   - numerics (duration/maxQuestions/pickCount/timers/attempts): CLAMP to the
 *     schema's range — an out-of-range number has a clear valid nearest value
 *     and clamping preserves the operator's intent ("long"/"many").
 *   - enums (difficulty/selectionMode/onWallHit): fall back to a safe default.
 * The result is then re-validated by gameSetUpsertSchema as the final gate.
 */
function cleanDraft(raw: unknown): GameSetUpsert | null {
  if (typeof raw !== "object" || raw === null) return null;
  const r = raw as Record<string, unknown>;
  const allowed = new Set(availableGames().map((g) => g.key as string));

  const rawGames = Array.isArray(r.games) ? r.games : [];
  const games = rawGames
    .filter(
      (g): g is Record<string, unknown> =>
        typeof g === "object" &&
        g !== null &&
        allowed.has((g as Record<string, unknown>).gameKey as string),
    )
    .map((g) => ({
      gameKey: g.gameKey as string,
      durationSeconds: clampInt(g.durationSeconds, 10, 3600, 300),
      startingDifficulty: DIFFICULTIES.has(g.startingDifficulty as string)
        ? (g.startingDifficulty as string)
        : "easy",
      allowSkip: typeof g.allowSkip === "boolean" ? g.allowSkip : true,
      maxQuestions: clampInt(g.maxQuestions, 0, 1000, 0),
      onWallHit: g.onWallHit === "reset" ? "reset" : "block",
    }));

  if (games.length === 0) return null; // nothing real to compose

  const selectionMode =
    r.selectionMode === "random_n_of_pool" ? "random_n_of_pool" : "fixed";
  const pickCount =
    selectionMode === "random_n_of_pool"
      ? clampInt(r.pickCount, 1, games.length, games.length)
      : undefined;

  const candidate = {
    title:
      typeof r.title === "string" && r.title.trim()
        ? r.title.trim().slice(0, 200)
        : "AI-drafted game set",
    description:
      typeof r.description === "string" ? r.description.slice(0, 2000) : "",
    games,
    selectionMode,
    pickCount,
    orgUnitIds: [],
    perQuestionTimerSeconds: clampInt(r.perQuestionTimerSeconds, 0, 600, 0),
    instantFeedback: r.instantFeedback === true,
    maxAttempts: clampInt(r.maxAttempts, 0, 100, 1),
    source: "ai_drafted" as const,
  };

  // Final gate: the real schema. If cleaning still didn't satisfy it, no draft.
  const parsed = gameSetUpsertSchema.safeParse(candidate);
  return parsed.success ? parsed.data : null;
}

export async function buildAiGameSetDraft(
  brief: string,
  opts: { collegeId?: string } = {},
): Promise<AiBuildGameSetResponse> {
  if (!hasLlmRouter()) return { configured: false, draft: null };

  const parsed = await callLlmChatJson(
    { url: "", apiKey: "", model: "", timeoutMs: 45_000 },
    SYSTEM_PROMPT,
    buildUserPrompt(brief, Boolean(opts.collegeId)),
    {
      kind: "generation",
      capability: "capable",
      maxTokens: 1200,
      feature: "game_build",
      ...(opts.collegeId ? { collegeId: opts.collegeId } : {}),
    },
  );

  // null = no usable output / exhausted credits / governor shed → compose manually.
  return { configured: true, draft: cleanDraft(parsed) };
}
