/**
 * Terms and Conditions — content shipped verbatim from the original CodeApt
 * template. Do not paraphrase or edit the legal copy.
 */
import { Container } from "../../components/layout/Container.js";
import { PageHeader } from "../../components/layout/PageHeader.js";
import { Prose, ProseSection } from "../../components/static/Prose.js";

const rulesOfUsage = [
  "To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.",
  "Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.",
  "Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.",
  "The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents.",
  "You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.",
  "You agree to pay us the charges associated with availing the Services.",
  "You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.",
];

export function TermsPage() {
  return (
    <Container size="md" className="py-12">
      <PageHeader title="Terms and Conditions" description="Last Updated: Dec 2025" />
      <Prose className="mt-8">
        <p>
          This document is an electronic record in terms of Information
          Technology Act, 2000 and rules there under as applicable and the
          amended provisions pertaining to electronic records in various
          statutes as amended by the Information Technology Act, 2000. This
          electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </p>
        <p>
          This document is published in accordance with the provisions of Rule 3
          (1) of the Information Technology (Intermediaries guidelines) Rules,
          2011 that require publishing the rules and regulations, privacy policy
          and Terms of Use for access or usage of domain name
          https://www.codeapt.in/ (&apos;Website&apos;), including the related
          mobile site and mobile application (hereinafter referred to as
          &apos;Platform&apos;).
        </p>

        <ProseSection title="Platform Ownership">
          <p>
            The Platform is owned by CODEAPT LLP, a company incorporated under
            the Companies Act, 1956 with its registered office at HNO 11 476 SHOP
            3 GAYATRI SATISH PLAZA SBH COLONY MOHAN NAGAR KOTHAPET SAROOR NAGAR
            (hereinafter referred to as &apos;Platform Owner&apos;, &apos;we&apos;,
            &apos;us&apos;, &apos;our&apos;).
          </p>
        </ProseSection>

        <ProseSection title="Terms of Use">
          <p>
            Your use of the Platform and services and tools are governed by the
            following terms and conditions (&quot;Terms of Use&quot;) as
            applicable to the Platform including the applicable policies which are
            incorporated herein by way of reference. If You transact on the
            Platform, You shall be subject to the policies that are applicable to
            the Platform for such transaction. By mere use of the Platform, You
            shall be contracting with the Platform Owner and these terms and
            conditions including the policies constitute Your binding obligations,
            with Platform Owner.
          </p>
          <p className="rounded-xl border border-subtle bg-surface-base p-4 font-medium text-ink">
            ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR
            AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO
            PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
          </p>
        </ProseSection>

        <ProseSection title="Rules of Usage">
          <ol className="list-decimal space-y-3 pl-5 marker:text-ink-muted">
            {rulesOfUsage.map((rule, i) => (
              <li key={i}>{rule}</li>
            ))}
          </ol>
        </ProseSection>

        <ProseSection title="Governing Law & Jurisdiction">
          <p>
            These Terms and any dispute or claim relating to it, or its
            enforceability, shall be governed by and construed in accordance with
            the laws of India. All disputes arising out of or in connection with
            these Terms shall be subject to the exclusive jurisdiction of the
            courts in Hyderabad and Telangana.
          </p>
        </ProseSection>

        <ProseSection title="Contact Us">
          <p>
            All concerns or communications relating to these Terms must be
            communicated to us using the contact information provided on this
            website.
          </p>
        </ProseSection>
      </Prose>
    </Container>
  );
}
